### ISSUE TITLE
(gnome-terminal is installed) /bin/sh: gnome-terminal: command not found

### ISSUE THREAD

**Issue by IgorSilvestre** [inouetoukyou/C_CppSingleFileBuilder_MinghangYang#2]
I have gnome-terminal and when I use /bin/sh directly it runs. What am I doing wrong?

**Comment by ytlw** [comment]
Hi, there. You may check if `gnome-ternimal` is in your PATH.  
use command `which gnome-ternimal` to see where `gnome-terminal` installed  
use command `echo $PATH` to list all your environment PATH.
