### ISSUE TITLE
MacOS not allowing the terminal to be opened.

### ISSUE THREAD

**Issue by Siddhant-sarkar** [inouetoukyou/C_CppSingleFileBuilder_MinghangYang#4]
“a” can’t be opened because (null) is not allowed to open documents in Terminal. is the  error that I am getting whenever it try the run option. it seem that Mac OS not allowing sublime to open terminal.
 Is there any solution for this problem.
<img width="266" alt="Screenshot 2022-12-19 at 3 26 05 PM" src="https://user-images.githubusercontent.com/66173271/208398471-738715c5-3460-4afb-b76d-cc1279df9f66.png">

**Comment by ytlw** [comment]
may be you can choose "build and run" option.

**Comment by Siddhant-sarkar** [comment]
Hey I switched from terminal.app to item.app and it works.
